export const BRAND = {
  name: 'Latimore Life & Legacy',
  fullName: 'Latimore Life & Legacy',
  tagline: 'Protecting Today. Securing Tomorrow.',
  hashtag: '#TheBeatGoesOn',
  cardUrl: 'https://card.latimorelifelegacy.com',
  advisor: 'Jackson M. Latimore Sr., Founder & CEO',
  affiliation: 'In Affiliation with Global Financial Impact',
  phone: '(717) 615-2613',
  phoneRaw: '7176152613',
  email: 'jackson1989@latimorelegacy.com',
  nipr: '21638507',
  paLicense: '1268820',
  bookingUrl: '/book',
  filloutUrl: 'https://latimorelifelegacy.fillout.com/latimorelifelegacy',
  ethosUrl: 'https://agents.ethoslife.com/invite/29ad1',
  instagram: 'https://www.instagram.com/jacksonlatimore.global',
  linkedin: 'https://www.linkedin.com/in/startwithjacksongfi',
  facebook: 'https://www.facebook.com/LatimoreLegacyLLC/',
  instagramUrl: 'https://www.instagram.com/jacksonlatimore.global',
  linkedinUrl: 'https://www.linkedin.com/in/startwithjacksongfi',
  facebookUrl: 'https://www.facebook.com/LatimoreLegacyLLC/',
  counties: ['Schuylkill', 'Luzerne', 'Northumberland'],
  baseUrl: process.env.NEXT_PUBLIC_BASE_URL ?? 'https://latimorelifelegacy.com',
} as const
