export const BRAND = {
  name: 'LATIMORE',
  fullName: 'Latimore Life & Legacy',
  tagline: 'Protecting Today. Securing Tomorrow.',
  advisor: 'Jackson M. Latimore Sr.',
  phone: '(856) 895-1457',
  email: 'jackson1989@latimorelegacy.com',
  nipr: '21638507',
  paLicense: '1268820',
  bookingUrl: 'https://calendly.com/jackson1989-latimorelegacy',
  ethosUrl: 'https://agents.ethoslife.com/invite/29ad1',
  filloutUrl: 'https://globalfinancialimpact.fillout.com/t/tMz7ZcqpaZus',
  counties: ['Schuylkill', 'Luzerne', 'Northumberland'],
  hashtag: '#TheBeatGoesOn',
} as const
